// components/app/dashboard/layout/Header.tsx
import { SidebarTrigger } from "@/components/ui/sidebar";
import HeaderLogo from "@/components/app/dashboard/layout/HeaderLogo";
import HeaderAvatar from "@/components/app/dashboard/layout/HeaderAvatar";

const Header = () => {
  return (
    <header className="flex shrink-0 items-center gap-2 border-b transition-[width,height] ease-linear">
      <div className="flex w-full items-center gap-1 px-4 lg:gap-2 lg:px-6 h-12">
        <SidebarTrigger className="-ml-1" />
        <HeaderLogo />
        <div className="ml-auto flex items-center gap-2">
          <HeaderAvatar />
        </div>
      </div>
    </header>
  );
};

export default Header;

// app/components/dashboard/layout/Header.vue
<script setup lang="ts">
import { Separator } from "@/components/ui/separator";
import { SidebarTrigger } from "@/components/ui/sidebar";
</script>

<template>
  <header
    class="flex h-(--header-height) shrink-0 items-center gap-2 border-b transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-(--header-height)"
  >
    <div class="flex w-full items-center gap-1 px-4 lg:gap-2 lg:px-6">
      <SidebarTrigger class="-ml-1" />
      <Separator
        orientation="vertical"
        class="mx-2 data-[orientation=vertical]:h-4"
      />
      <h1 class="text-base font-medium">Documents</h1>
      <div class="ml-auto flex items-center gap-2">
        <DashboardLayoutHeaderAvatar />
      </div>
    </div>
  </header>
</template>
