// app/(public)/profile/[username]/page.tsx
import { Metadata } from "next";
import { notFound } from "next/navigation";
import { API_URL, SITE_URL } from "@/constant/index.constant";
import { ApiResponse } from "@/server/types";
import type { ProfileInterface } from "@/types/profile.types";
import ProfileTop from "@/components/app/public/profile/ProfileTop";
import ProfileAllThemesByUserName from "@/components/app/public/profile/ProfileAllThemesByUserName";

interface Params {
  username: string;
}

interface Props {
  params: Promise<Params>;
  searchParams: Promise<{
    page?: string;
    term?: string;
    filter?: string;
  }>;
}

const fetchProfile = async (username: string) => {
  const res = await fetch(`${API_URL}/profile/${username}`, {
    next: {
      revalidate: 120,
    },
  });

  if (!res.ok) return null;

  const json: ApiResponse<ProfileInterface> = await res.json();
  if (!json.success || !json.data) return null;

  return json.data;
};

export const generateMetadata = async ({
  params,
}: Props): Promise<Metadata> => {
  const { username } = await params;
  const profile = await fetchProfile(username);

  const title = profile
    ? `${profile.user_name} user profile`
    : "User profile not found";
  const description = profile
    ? `${profile.user_name} user profile, with full name ${profile.full_name} - APIBolt.`
    : "Following user profile not found - APIBolt.";

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      images: [`${SITE_URL}/og.png`],
      url: `${SITE_URL}/profile/${username}`,
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [`${SITE_URL}/og.png`],
    },
  };
};

const Page = async ({ params, searchParams }: Props) => {
  const { username } = await params;
  const profile = await fetchProfile(username);

  if (!profile) notFound();

  return (
    <section className="w-full container mx-auto flex flex-col pt-30">
      <div className="relative">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-175 h-175 bg-primary/20 rounded-full blur-[150px] pointer-events-none opacity-50" />
        <ProfileTop profile={profile} className="p-4" />
      </div>
      <ProfileAllThemesByUserName
        username={username}
        searchParams={searchParams}
        className="px-4"
      />
    </section>
  );
};

export default Page;

// app/pages/(public)/profile/[username].vue
<template>
  <section class="w-full container mx-auto flex flex-col">
    <ProfileUserDetailsSkeleton v-if="pending" />
    <NotFound
      v-else-if="isNotFound"
      :description="`User ${userName} not found`"
      class="flex-1"
    />
    <template v-else>
      <div class="relative">
        <div
          class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] h-[700px] bg-primary/20 rounded-full blur-[150px] pointer-events-none opacity-50"
        />
        <ProfileTop :profile="data!.data!" class="p-4" />
      </div>
      <ProfileAllThemesByUserName :username="userName" class="px-4" />
    </template>
  </section>
</template>

<script setup lang="ts">
import NotFound from "~/components/ui/not-found/NotFound.vue";
import type { ProfileInterface } from "~/types/profile.types";
import type { ApiResponse } from "~~/server/types";

const route = useRoute();
const userName = computed(() => route.params["username"] as string);

const { data, pending, error } = await useFetch<ApiResponse<ProfileInterface>>(
  () => `/api/v1/profile/${userName.value}`,
  {
    key: `profile-${userName.value}`,
  },
);

const isNotFound = computed(
  () => error.value || data.value?.success === false || !data.value?.data,
);

/* SEO ====================== */
const seoTitle = computed(() => {
  if (pending.value) return "Loading profile...";
  return data.value?.data?.user_name
    ? `${data.value.data.user_name} user profile`
    : "User profile not found";
});

const seoDescription = computed(() => {
  if (pending.value) return "Loading... - APIBolt";
  return data.value?.data?.user_name
    ? `${data.value.data.user_name} user profile, with full name ${data.value.data.full_name} - APIBolt.`
    : "Following user profile not found - APIBolt.";
});
const seoImage = computed(() => data.value?.data?.avatar_url || "/logo.svg");

useHead({
  title: seoTitle,
  meta: [
    { name: "description", content: seoDescription },
    { property: "og:title", content: seoTitle },
    { property: "og:description", content: seoDescription },
    { property: "og:image", content: seoImage },
    { property: "og:type", content: "website" },

    { name: "twitter:card", content: "summary_large_image" },
    { name: "twitter:title", content: seoTitle },
    { name: "twitter:image", content: seoImage },
  ],
});
</script>
