// app/error.tsx
"use client";

import { Button } from "@/components/ui/button";
import Link from "next/link";

interface ErrorProps {
  error: Error;
  reset: () => void;
}

export default function Error({ error, reset }: ErrorProps) {
  return (
    <div className="min-h-[70vh] flex flex-col items-center justify-center container mx-auto px-4">
      <h2 className="text-2xl md:text-3xl font-bold mb-4 text-center">
        Something went wrong!
      </h2>

      <p className="text-muted-foreground mb-8 text-center max-w-md">
        {error.message ||
          "An unexpected error occurred while processing your request."}
      </p>

      <div className="flex flex-col sm:flex-row gap-4">
        <Button variant="outline" onClick={reset} className="cursor-pointer">
          Try again
        </Button>
        <Link href="/">
          <Button
            variant="secondary"
            className="cursor-pointer text-muted-foreground hover:text-foreground"
          >
            Return Home
          </Button>
        </Link>
      </div>
    </div>
  );
}

// app/error.vue
<template>
  <div class="min-h-[70vh] flex flex-col items-center justify-center">
    <NotFound
      :description="
        error.statusCode === 404
          ? 'The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.'
          : error.message || 'Something went wrong on our end.'
      "
    />
    <div
      v-if="error.statusCode !== 404"
      class="mt-8 flex flex-col items-center gap-4"
    >
      <p
        class="text-sm text-muted-foreground font-mono bg-muted/30 px-3 py-1 rounded-md"
      >
        Code: {{ error.statusCode }}
      </p>
      <Button variant="outline" @click="handleError" class="cursor-pointer">
        Try again
      </Button>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { NuxtError } from "#app";

definePageMeta({
  layout: "default",
});

const props = defineProps<{
  error: NuxtError;
}>();

const handleError = () =>
  clearError({
    redirect: "/",
  });

useSeoMeta({
  title:
    props.error.statusCode === 404
      ? "Page Not Found | ApiBolt"
      : "Error Occurred | ApiBolt",
  description:
    props.error.message || "An error occurred while processing your request.",
});
</script>
