// app/pages/not-found.vue
<template>
  <div class="container mx-auto px-4">
    <NotFound
      description="The page you're looking for doesn't exist. It might have been moved or deleted."
      class="min-h-[70vh]"
    />
  </div>
</template>

<script setup lang="ts">
import { NotFound } from "~/components/ui/not-found";

useSeoMeta({
  title: "Page Not Found | ApiBolt",
  description: "The requested page could not be found on ApiBolt.",
});
</script>

// app/not-found.tsx
import NotFound from "@/components/ui/not-found";

const Page = () => {
  return (
    <div className="mx-auto px-4 flex-1 flex justify-center items-center overflow-hidden w-full">
      <NotFound
        description="The page you're looking for doesn't exist. It might have been moved or deleted."
        className="min-h-[70vh] container"
      />
    </div>
  );
};

export default Page;
