// app/components/dashboard/layout/NavItem.vue
<script setup lang="ts">
import type { Component } from "vue";
import { SidebarMenuButton, SidebarMenuItem } from "@/components/ui/sidebar";

interface NavItem {
  title: string;
  url?: string;
  icon?: Component;
}

defineProps<{
  item: NavItem;
}>();
</script>

<template>
  <SidebarMenuItem class="select-none">
    <NuxtLink v-if="item.url" :href="item.url">
      <SidebarMenuButton :tooltip="item.title" class="cursor-pointer">
        <component :is="item.icon" v-if="item.icon" />
        <span>{{ item.title }}</span>
      </SidebarMenuButton>
    </NuxtLink>
    <SidebarMenuButton v-else :tooltip="item.title">
      <component :is="item.icon" v-if="item.icon" />
      <span>{{ item.title }}</span>
    </SidebarMenuButton>
  </SidebarMenuItem>
</template>

// components/app/dashboard/layout/NavItem.tsx
import Link from "next/link";
import { SidebarMenuItem } from "@/components/ui/sidebar";
import { NavItemInterface } from "@/types/dashboard.types";
import NavItemWrapper from "@/components/app/dashboard/layout/NavItemWrapper";

interface Props {
  item: NavItemInterface;
}

const DashboardLayoutNavItem = ({ item }: Props) => {
  const { title, Icon, url } = item;

  return (
    <SidebarMenuItem className="select-none">
      {url ? (
        <Link href={url}>
          <NavItemWrapper title={title} url={url}>
            {Icon && <Icon />}
            <span>{title}</span>
          </NavItemWrapper>
        </Link>
      ) : (
        <NavItemWrapper title={title} url={url}>
          {Icon && <Icon />}
          <span>{title}</span>
        </NavItemWrapper>
      )}
    </SidebarMenuItem>
  );
};

export default DashboardLayoutNavItem;
